from __future__ import annotations

STABLE_FOR_AGENTS = "stable_for_agents"
BETA_FOR_AGENTS = "beta_for_agents"
HUMAN_ORIENTED = "human_oriented"
REPAIR = "repair"

COMMAND_METADATA: dict[str, tuple[str, str]] = {
    "init": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "status": (STABLE_FOR_AGENTS, "safe_read_only"),
    "next-action": (STABLE_FOR_AGENTS, "safe_read_only"),
    "view": (STABLE_FOR_AGENTS, "safe_read_only"),
    "can": (STABLE_FOR_AGENTS, "safe_read_only"),
    "reindex": (REPAIR, "ledger_mutation"),
    "export": (STABLE_FOR_AGENTS, "safe_read_only"),
    "import": (REPAIR, "ledger_mutation"),
    "snapshot": (STABLE_FOR_AGENTS, "safe_read_only"),
    "context": (STABLE_FOR_AGENTS, "safe_read_only"),
    "search": (BETA_FOR_AGENTS, "safe_read_only"),
    "grep": (BETA_FOR_AGENTS, "safe_read_only"),
    "symbols": (BETA_FOR_AGENTS, "safe_read_only"),
    "deps": (BETA_FOR_AGENTS, "safe_read_only"),
    "task create": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "task list": (STABLE_FOR_AGENTS, "safe_read_only"),
    "task active": (STABLE_FOR_AGENTS, "safe_read_only"),
    "task activate": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "task deactivate": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "task show": (STABLE_FOR_AGENTS, "safe_read_only"),
    "task edit": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "task cancel": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "task close": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "task dossier": (STABLE_FOR_AGENTS, "safe_read_only"),
    "task events": (STABLE_FOR_AGENTS, "safe_read_only"),
    "plan start": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "plan propose": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "plan draft": (STABLE_FOR_AGENTS, "safe_read_only"),
    "plan regenerate": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "plan upsert": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "plan materialize-todos": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "plan show": (STABLE_FOR_AGENTS, "safe_read_only"),
    "plan list": (STABLE_FOR_AGENTS, "safe_read_only"),
    "plan diff": (STABLE_FOR_AGENTS, "safe_read_only"),
    "plan approve": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "plan accept": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "plan command": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "plan reject": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "plan revise": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "question add": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "question list": (STABLE_FOR_AGENTS, "safe_read_only"),
    "question answer": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "question answer-many": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "question dismiss": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "question open": (STABLE_FOR_AGENTS, "safe_read_only"),
    "question status": (STABLE_FOR_AGENTS, "safe_read_only"),
    "question answers": (STABLE_FOR_AGENTS, "safe_read_only"),
    "implement start": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "implement log": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "implement change": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "implement scan-changes": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "implement command": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "implement deviation": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "implement artifact": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "implement finish": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "implement show": (STABLE_FOR_AGENTS, "safe_read_only"),
    "implement status": (STABLE_FOR_AGENTS, "safe_read_only"),
    "implement checklist": (STABLE_FOR_AGENTS, "safe_read_only"),
    "validate start": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "validate check": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "validate finish": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "validate status": (STABLE_FOR_AGENTS, "safe_read_only"),
    "validate waive": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "validate show": (STABLE_FOR_AGENTS, "safe_read_only"),
    "todo add": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "todo list": (STABLE_FOR_AGENTS, "safe_read_only"),
    "todo done": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "todo undone": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "todo show": (STABLE_FOR_AGENTS, "safe_read_only"),
    "todo status": (STABLE_FOR_AGENTS, "safe_read_only"),
    "todo next": (STABLE_FOR_AGENTS, "safe_read_only"),
    "intro create": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "intro list": (STABLE_FOR_AGENTS, "safe_read_only"),
    "intro show": (STABLE_FOR_AGENTS, "safe_read_only"),
    "intro link": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "file add": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "file remove": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "file list": (STABLE_FOR_AGENTS, "safe_read_only"),
    "link add": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "link list": (STABLE_FOR_AGENTS, "safe_read_only"),
    "link remove": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "require add": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "require list": (STABLE_FOR_AGENTS, "safe_read_only"),
    "require remove": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "require waive": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "lock show": (REPAIR, "safe_read_only"),
    "lock break": (REPAIR, "ledger_mutation"),
    "lock list": (REPAIR, "safe_read_only"),
    "handoff show": (STABLE_FOR_AGENTS, "safe_read_only"),
    "handoff create": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "handoff list": (STABLE_FOR_AGENTS, "safe_read_only"),
    "handoff claim": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "handoff close": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "handoff cancel": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "handoff plan-context": (STABLE_FOR_AGENTS, "safe_read_only"),
    "handoff implementation-context": (STABLE_FOR_AGENTS, "safe_read_only"),
    "handoff validation-context": (STABLE_FOR_AGENTS, "safe_read_only"),
    "actor whoami": (STABLE_FOR_AGENTS, "safe_read_only"),
    "actor set": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "actor clear": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "harness set": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "harness clear": (STABLE_FOR_AGENTS, "ledger_mutation"),
    "doctor": (REPAIR, "safe_read_only"),
    "doctor locks": (REPAIR, "safe_read_only"),
    "doctor schema": (REPAIR, "safe_read_only"),
    "doctor indexes": (REPAIR, "safe_read_only"),
    "repair index": (REPAIR, "ledger_mutation"),
    "repair lock": (REPAIR, "ledger_mutation"),
    "repair task": (REPAIR, "ledger_mutation"),
    "repair task-dirs": (REPAIR, "ledger_mutation"),
}
